# START: probes
# START: beginning
FROM golang:1.25.1-alpine AS build
WORKDIR /go/src/proglog
COPY . .
RUN CGO_ENABLED=0 go build -o /go/bin/proglog ./cmd/proglog
# END: beginning
# START_HIGHLIGHT
RUN export GRPC_HEALTH_PROBE_VERSION=v0.4.41 && \
    wget -q -O /go/bin/grpc_health_probe \
    "https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64" && \
    chmod +x /go/bin/grpc_health_probe

# END_HIGHLIGHT
# START: beginning

FROM scratch
COPY --from=build /go/bin/proglog /bin/proglog
# END: beginning
# START_HIGHLIGHT
COPY --from=build /go/bin/grpc_health_probe /bin/grpc_health_probe
# END_HIGHLIGHT
# START: beginning
ENTRYPOINT ["/bin/proglog"]
# END: beginning
# END: probes